### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by CrahunGit** [Blazored/Toast#113] opened 2021-04-17 11:51 UTC
How can I change error icon when calling toastService.ShowError? I don't want to see mainlayout icon every time. 
If put any other BlazoredToasts element on page I see two toast instead on one.

**Comment by chrissainty** [comment] 2021-04-17 12:36
You can't change the icon on a case by case basis right now. You can only set a global icon. Closing a duplicate of #75

**Closed by chrissainty** 2021-04-17 12:36 UTC
Labels: Question, Triage
