### ISSUE TITLE
[Question] Is .Net 8 supported? What is the correct way to initialize it?

### ISSUE THREAD

**Issue by kidmar** [Blazored/Toast#243] opened 2023-11-23 17:31 UTC
I create a new .Net 8 Blazor server app.
I can get the toast to show, but it looks like some css is missing.
Where should I reference the missing css and how?

![immagine](https://github.com/Blazored/Toast/assets/4757146/ec3dc44b-4119-4721-ba47-186fe3407fa2)

**Comment by bcheung4589** [comment] 2023-11-24 13:41
Go back to 4.0.0 the upgrade is broken. If you wait for response of @chrissainty it might take weeks..

**Comment by kidmar** [comment] 2023-11-24 15:24
Thank you, v4.0.0 works

**Comment by UweKeim** [comment] 2023-12-05 18:32
In my .NET 8 Blazor App (non-server), I did not manage to get this working, even with 4.0.0. 

In my .NET 8 server-size Blazor app, it is working.

I guess the new server/client modes are not supported by Blazored Toast (yet?)

**Comment by Dimnis-git** [comment] 2023-12-05 18:41
I'm testing this and only work with render mode Interactive Server

**Comment by rennera** [comment] 2023-12-14 19:52
Did anyone get this to work with .Net 8 - I am testing and have not had any luck.  I have used previous versions for a few years and its great.  Getting no love from version 3.2.2, 4.0.0, 4.1.0 in .net8  - working on Server Side app

**Comment by UweKeim** [comment] 2023-12-14 19:56
It seems, that all my favorite Blazor library developers have shifted priorities away from .NET 8 Blazor 😭.

**Comment by chrissainty** [comment] 2023-12-14 19:57
Hello all and apologies for the lack of comms. I have a lot going on right now and haven't had time to look at the changes needed for .NET 8. I'm hoping to spend some time on this over the Christmas break

**Comment by rennera** [comment] 2023-12-14 23:15
I fully understand the competing priorities :)  Maybe I am just to quick on the uptake of .net8!  Happy holidays!

**Comment by UweKeim** [comment] 2023-12-18 19:21
In case it might help @chrissainty, I was able to work-around a similar Issue in the Razor.SweetAlert2 library for Blazor .NET 8, see this comment of user [@PvxTotal](https://github.com/Pvxtotal):

https://github.com/Basaingeal/Razor.SweetAlert2/issues/2642#issuecomment-1860420919

Maybe this gives some pointers for solving it here, too.

**Comment by dvzghr** [comment] 2024-01-30 21:51
.NET8 webapp Server: it is only working for me when I place the `<BlazoredToasts  />` as part of the component and not inside `MainLayout`
same for 4.0.0 and 4.1.0

**Comment by dvzghr** [comment] 2024-01-30 21:54
> 
> In my .NET 8 server-size Blazor app, it is working.
> 

@UweKeim did you place the `<BlazoredToasts />` inside the `MainLayout`? and it works for you then?

**Comment by UweKeim** [comment] 2024-01-31 06:09
@dvzghr It _only_ works in a _server-side_ Blazor app that I migrated over the years from .NET 6 → .NET 7 → .NET 8.

It does _not_ work in a freshly created .NET 8 Blazor app.

**Comment by Stefan13-13** [comment] 2024-02-01 13:12
I created a new Blazor Web App in .NET8 and cannot get this library to work. Just nothing is showing up (I added the <BlazoredToasts/> to MainLayout.razor).

**Comment by chrissainty** [comment] 2024-02-01 14:34
Did you create an interactive web app or a SSR one?

**Comment by Stefan13-13** [comment] 2024-02-01 14:49
Did all the steps in the readme. And no toasts showing up when pressing the buttons.

Using Visual Studio 2022, I created a 'Blazor Web App' project.
Then selected:

- .NET 8.0 LTS
- None for Authetnication type,
- Checked Configure for HTTPS
- Server for Interactive render mode.
- Per page/component for Interactivity location
- Checked Include sample pages
- Unchecked Do not use top-level statements.

Also using VS2022, when I create an '.NET 7 Blazor Server App' project, and do the steps in the readme, all works out of the box in 1 go. If I change then the framework type of this project to .NET 8, it still works. So it seems the problem has something to do with the changes in the .NET 8 Blazor Web App template.

**Comment by dvzghr** [comment] 2024-02-01 18:22
> Did you create an interactive web app or a SSR one?

interactive server web app

**Comment by Stefan13-13** [comment] 2024-02-02 08:25
No, when creating a .NET 8.0 template project as I state above, it also does NOT work when placing the `<BlazoredToasts />` on the component page.

I also tested setting the Interactivity location Globally (to InteractiveServer, in app.razor using the `<HeadOutlet>` and `<Routes>` tags, as opposed to Per page/component as interactivity location as I stated above when created the template project). Still no change, no toasts showing.

**Comment by rennera** [comment] 2024-02-02 15:28
@UweKeim it certainly has its usability issues doesn't it!  I want to use it but just cannot upgrade existing apps - too many issues like you stated.

On a side - I tried Radzen and Syncfusion with .Net8 and was able to get the syncfusion toasts working in the meantime.  Once these are working again I will switch them back.

**Comment by chrissainty** [comment] 2024-02-02 16:05
For those that have said they have created an interactive app, have you added the following to the components in the `App` component?

```razor
<HeadOutlet @rendermode="InteractiveServer"/>
...
<Routes @rendermode="InteractiveServer"/>
```

without adding these the application will not be interactive. I've just done this and the package seems to work fine from what I can see. These new render modes are tricky.

**Comment by rennera** [comment] 2024-02-02 17:20
just tried this and the blazored toast works with those changes...
![image](https://github.com/Blazored/Toast/assets/3689865/c628cab1-f9dc-46c1-ada8-75dcaddc419d)

**Comment by chrissainty** [comment] 2024-02-02 18:23
@rennera Thanks for confirming. The current templates are misleading in that it doesn't matter what you pick nothing is fully interactive till you add those attributes.

**Comment by UweKeim** [comment] 2024-02-02 18:50
Back then I've tried these

```blazor
<HeadOutlet @rendermode="InteractiveServer"/>
...
<Routes @rendermode="InteractiveServer"/>
```

And had all sort of malfunction in other areas then. (Don't know for sure where but I do think it was in the boilerplate authentication components added by the project wizard).

So personally I would _not_ recommend using these above attributes.

**Comment by Stefan13-13** [comment] 2024-02-02 18:54
> For those that have said they have created an interactive app, have you added the following to the components in the `App` component?
> 
> ```
> <HeadOutlet @rendermode="InteractiveServer"/>
> ...
> <Routes @rendermode="InteractiveServer"/>
> ```
> 
> Without adding these the application will not be interactive. I've just done this and the package seems to work fine from what I can see. These new render modes are tricky.

Just for reference:
You get those by default when you create a new .NET 8 Blazor Web App project and select 'Global' as Interactivity location (as opposed to the default 'Per page/component'. But you can also change the manually.

Setting the rendermode to InteractiveServer globally makes it work! If you set it on a single page, it does not work (except when you put `<BlazoredToasts />` also on that page).

**Comment by Stefan13-13** [comment] 2024-02-02 18:59
> Back then I've tried these:
> 
> ```
> <HeadOutlet @rendermode="InteractiveServer"/>
> ...
> <Routes @rendermode="InteractiveServer"/>
> ```
> 
> I've had all sort of malfunction in other areas after this. (Don't know for sure where but I do think it was in the boilerplate authentication components added by the project wizard).
> 
> So personally I would _not_ recommend using these above attributes.

A bit off topic, but in case you have trouble with setting InteractiveServer globally, then try this:

```
<HeadOutlet @rendermode="@(new InteractiveServerRenderMode(prerender: false))" />
...
<Routes @rendermode="@(new InteractiveServerRenderMode(prerender: false))" />
```

By default, prerendering is enabled for InteractiveServer and it will cause issues if you have stuff that only works on the client side (like Blazored.LocalStorage). The above disables prerendering globally.

**Comment by chrissainty** [comment] 2024-02-02 19:24
@Stefan13-13 

> If you set it on a single page, it does not work (except when you put <BlazoredToasts /> also on that page).

Yes. This is part of the fun of the new render modes. Interactive libraries, such as this one, can only work on interactive pages. Just to be clear this is by design and there are no changes I can do to make this behave any differently.

**Comment by rennera** [comment] 2024-02-03 05:21
I had the same malfunctions on the boilerplate pages like register/login etc

**Comment by vicsind** [comment] 2024-02-06 00:22
I can also advice to wrap the **BlazoredToasts** component to your own component (for example you can name it ToastsContainer) and set **@rendermode InteractiveServer** for this component.
![image](https://github.com/Blazored/Toast/assets/22524136/07da8798-76bd-4aae-a014-bffa2f0281d2)

After that just use your new
**<ToastsContainer />** 
in your main layout.

**Comment by chrissainty** [comment] 2024-02-19 19:14
I'm going to close this issue as the package does work with .NET 8, but .NET 8 has a rather steep learning curve compared to previous Blazor releases and setting `rendermodes` incorrectly in your app will stop the library working.

**Closed by chrissainty** 2024-02-19 19:14 UTC
Labels: Question, Triage

**Comment by iburleigh** [comment] 2024-04-04 18:06
You can follow the documentation exactly and get this to work by adding @rendermode="InteractiveServer" directly to the BlazoredToasts component (see below). Adding the rendermode higher in the app such as to routes and headoutlet forces the entire app into server interactive, which is not desired for everyone and will explode .Net8 Identity pages if you scaffolded them. 

```
<BlazoredToasts @rendermode="InteractiveServer"
                Position="ToastPosition.BottomRight"
                Timeout="10"
                RemoveToastsOnNavigation="true"
                MaxToastCount="5"
                IconType="IconType.FontAwesome"
                SuccessClass="success-toast-override"
                SuccessIcon="fa fa-thumbs-up"
                ErrorIcon="fa fa-exclamation"/>
```

**Comment by BillDahl** [comment] 2024-05-03 22:52
Putting @rendermode InteractiveServer at the top of a component also seems to make it work (using Typeahead in my case).
